# Generated by Django 5.2.5 on 2025-09-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_amount',
        ),
    ]
